version: '3.5'

services:
  ec2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ec2_container
    tty: true
    environment:
      - SSH_KEU=value
    volumes: # This is just for local
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      ec2-network:
        ipv4_address: 192.168.80.2

networks:
    ec2-network:
      external: true