version: '3.5'

services:
  ec2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SSH_KEY=${SSH_KEY}
    container_name: ec2_container
    tty: true
    volumes: # This is just for local
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/tmp/cluster:/var/tmp/cluster
      - /var/lib/docker/containers:/var/lib/docker/containers
    networks:
      ec2-network:
        ipv4_address: 192.168.80.2

networks:
    ec2-network:
      external: true